const fs = require('fs');
const path = require('path');

const routes = [
  { path: 'organizations', title: 'Organizations', entity: 'Organization', cols: ['Name', 'Plan', 'Users', 'Status', 'Created'] },
  { path: 'users', title: 'Users', entity: 'User', cols: ['Name', 'Email', 'Role', 'Status', 'Last Login'] },
  { path: 'roles', title: 'Roles', entity: 'Role', cols: ['Role Name', 'Description', 'Permissions', 'Users'] },
  { path: 'permissions', title: 'Permissions', entity: 'Permission', cols: ['Permission', 'Description', 'Module'] },
  { path: 'departments', title: 'Departments', entity: 'Department', cols: ['Department Name', 'Head', 'Members'] },
  { path: 'plants', title: 'Plants', entity: 'Plant', cols: ['Plant Name', 'Location', 'Manager', 'Status'] },
  { path: 'assets', title: 'Assets', entity: 'Asset', cols: ['Asset ID', 'Name', 'Category', 'Status'] },
  { path: 'asset-categories', title: 'Asset Categories', entity: 'Category', cols: ['Category Name', 'Assets Count', 'Description'] },
  { path: 'document-categories', title: 'Document Categories', entity: 'Category', cols: ['Name', 'Description', 'Documents Count'] },
  { path: 'document-templates', title: 'Document Templates', entity: 'Template', cols: ['Template Name', 'Type', 'Last Updated'] },
  { path: 'documents', title: 'Documents', entity: 'Document', cols: ['Document ID', 'Title', 'Category', 'Status', 'Date'] },
  { path: 'knowledge-graph', title: 'Knowledge Graph', entity: 'Node', cols: ['Node ID', 'Label', 'Connections', 'Last Updated'] },
  { path: 'ai', title: 'AI Center', entity: 'Configuration', cols: ['Module', 'Status', 'Usage', 'Cost'] },
  { path: 'ai/models', title: 'AI Models', entity: 'Model', cols: ['Model Name', 'Provider', 'Status', 'Requests'] },
  { path: 'ai/agents', title: 'AI Agents', entity: 'Agent', cols: ['Agent Name', 'Type', 'Status', 'Tasks Completed'] },
  { path: 'ai/prompts', title: 'Prompt Library', entity: 'Prompt', cols: ['Prompt Name', 'Category', 'Version', 'Last Edited'] },
  { path: 'ocr', title: 'OCR Center', entity: 'Engine', cols: ['Engine Name', 'Jobs Processed', 'Success Rate', 'Status'] },
  { path: 'vector-db', title: 'Vector Database', entity: 'Collection', cols: ['Collection Name', 'Vectors Count', 'Dimension', 'Size'] },
  { path: 'embeddings', title: 'Embeddings', entity: 'Model', cols: ['Model Name', 'Dimension', 'Status'] },
  { path: 'reports', title: 'Reports', entity: 'Report', cols: ['Report Name', 'Type', 'Generated By', 'Date'] },
  { path: 'analytics', title: 'Analytics', entity: 'Dashboard', cols: ['Dashboard Name', 'Views', 'Last Updated'] },
  { path: 'notifications', title: 'Notifications', entity: 'Notification', cols: ['Title', 'Type', 'Sent To', 'Date'] },
  { path: 'audit', title: 'Audit Logs', entity: 'Log Entry', cols: ['Action', 'User', 'Resource', 'IP Address', 'Timestamp'] },
  { path: 'security', title: 'Security Center', entity: 'Policy', cols: ['Policy Name', 'Severity', 'Status', 'Last Triggered'] },
  { path: 'system', title: 'System Monitoring', entity: 'Metric', cols: ['Service', 'Status', 'Uptime', 'CPU/Memory'] },
  { path: 'jobs', title: 'Background Jobs', entity: 'Job', cols: ['Job ID', 'Type', 'Status', 'Duration', 'Started'] },
  { path: 'queues', title: 'Queues', entity: 'Queue', cols: ['Queue Name', 'Pending', 'Processed', 'Failed'] },
  { path: 'storage', title: 'Storage', entity: 'Bucket', cols: ['Bucket Name', 'Size', 'Object Count', 'Region'] },
  { path: 'backup', title: 'Backup & Restore', entity: 'Backup', cols: ['Backup ID', 'Type', 'Size', 'Status', 'Date'] },
  { path: 'api', title: 'API Management', entity: 'API Key', cols: ['Key Name', 'Owner', 'Status', 'Last Used'] },
  { path: 'integrations', title: 'Integrations', entity: 'Integration', cols: ['Service', 'Status', 'Sync Frequency', 'Last Sync'] },
  { path: 'billing', title: 'Billing', entity: 'Invoice', cols: ['Invoice ID', 'Amount', 'Status', 'Date'] },
  { path: 'subscriptions', title: 'Subscriptions', entity: 'Subscription', cols: ['Plan', 'Organization', 'Status', 'Renewal Date'] },
  { path: 'licenses', title: 'Licenses', entity: 'License', cols: ['License Key', 'Type', 'Assigned To', 'Expires'] },
  { path: 'features', title: 'Feature Flags', entity: 'Flag', cols: ['Feature Name', 'Key', 'Status', 'Rollout %'] },
  { path: 'settings', title: 'Settings', entity: 'Setting', cols: ['Category', 'Description', 'Last Modified'] },
  { path: 'help', title: 'Help Center', entity: 'Article', cols: ['Article Title', 'Category', 'Views', 'Last Updated'] },
  { path: 'profile', title: 'Profile Settings', entity: 'Preference', cols: ['Setting', 'Value'] },
];

const adminBasePath = path.join(__dirname, '..', 'src', 'app', 'admin');

routes.forEach(route => {
  const dirPath = path.join(adminBasePath, route.path);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  const content = `"use client";

import { AdminPageTemplate } from "@/components/ui/AdminPageTemplate";

export default function ${route.path.split('/').pop().replace(/-/g, '').replace(/^\w/, c => c.toUpperCase())}Page() {
  return (
    <AdminPageTemplate
      title="${route.title}"
      description="Manage and configure ${route.title.toLowerCase()} for the platform."
      entityName="${route.entity}"
      columns={${JSON.stringify(route.cols)}}
    />
  );
}
`;

  fs.writeFileSync(path.join(dirPath, 'page.tsx'), content, 'utf8');
  console.log(`Created route: /admin/${route.path}`);
});
