"""Make org_id nullable

Revision ID: 8b23398fbe73
Revises: 57cb8d782097
Create Date: 2026-06-30 18:45:22.820318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b23398fbe73'
down_revision: Union[str, Sequence[str], None] = '57cb8d782097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
