"""Pipeline Documents

Revision ID: 994006216040
Revises: da379af153df
Create Date: 2026-06-24 19:05:18.610584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994006216040'
down_revision: Union[str, Sequence[str], None] = 'da379af153df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_metadata',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('qdrant_collection_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_metadata_checksum_sha256'), 'document_metadata', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_document_metadata_deleted_at'), 'document_metadata', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_metadata_id'), 'document_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_document_metadata_org_id'), 'document_metadata', ['org_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_status'), 'document_metadata', ['status'], unique=False)
    op.create_index(op.f('ix_document_metadata_uploaded_by_id'), 'document_metadata', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_metadata_uploaded_by_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_status'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_org_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_deleted_at'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_checksum_sha256'), table_name='document_metadata')
    op.drop_table('document_metadata')
    # ### end Alembic commands ###
