"""Init Enterprise DMS

Revision ID: 9b51f199f19f
Revises: 01e6cf76a81d
Create Date: 2026-06-30 17:36:52.078198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b51f199f19f'
down_revision: Union[str, Sequence[str], None] = '01e6cf76a81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dms_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dms_categories_deleted_at'), 'dms_categories', ['deleted_at'], unique=False)
    op.create_table('dms_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dms_tags_deleted_at'), 'dms_tags', ['deleted_at'], unique=False)
    op.create_table('dms_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['dms_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_folders_deleted_at'), 'dms_folders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dms_folders_org_id'), 'dms_folders', ['org_id'], unique=False)
    op.create_index(op.f('ix_dms_folders_parent_id'), 'dms_folders', ['parent_id'], unique=False)
    op.create_table('dms_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confidentiality', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dms_categories.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['dms_folders.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_documents_deleted_at'), 'dms_documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dms_documents_document_number'), 'dms_documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_dms_documents_folder_id'), 'dms_documents', ['folder_id'], unique=False)
    op.create_index(op.f('ix_dms_documents_org_id'), 'dms_documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_dms_documents_status'), 'dms_documents', ['status'], unique=False)
    op.create_table('dms_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_audit_logs_deleted_at'), 'dms_audit_logs', ['deleted_at'], unique=False)
    op.create_table('dms_document_tags',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('tag_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['dms_tags.id'], ondelete='CASCADE')
    )
    op.create_table('dms_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('ai_status', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.String(length=2000), nullable=True),
    sa.Column('qdrant_collection_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_versions_checksum_sha256'), 'dms_versions', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_dms_versions_deleted_at'), 'dms_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dms_versions_document_id'), 'dms_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_dms_versions_is_current'), 'dms_versions', ['is_current'], unique=False)
    op.create_table('dms_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['dms_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dms_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_approvals_deleted_at'), 'dms_approvals', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'departments', 'users', ['head_of_department_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_dms_approvals_deleted_at'), table_name='dms_approvals')
    op.drop_table('dms_approvals')
    op.drop_index(op.f('ix_dms_versions_is_current'), table_name='dms_versions')
    op.drop_index(op.f('ix_dms_versions_document_id'), table_name='dms_versions')
    op.drop_index(op.f('ix_dms_versions_deleted_at'), table_name='dms_versions')
    op.drop_index(op.f('ix_dms_versions_checksum_sha256'), table_name='dms_versions')
    op.drop_table('dms_versions')
    op.drop_table('dms_document_tags')
    op.drop_index(op.f('ix_dms_audit_logs_deleted_at'), table_name='dms_audit_logs')
    op.drop_table('dms_audit_logs')
    op.drop_index(op.f('ix_dms_documents_status'), table_name='dms_documents')
    op.drop_index(op.f('ix_dms_documents_org_id'), table_name='dms_documents')
    op.drop_index(op.f('ix_dms_documents_folder_id'), table_name='dms_documents')
    op.drop_index(op.f('ix_dms_documents_document_number'), table_name='dms_documents')
    op.drop_index(op.f('ix_dms_documents_deleted_at'), table_name='dms_documents')
    op.drop_table('dms_documents')
    op.drop_index(op.f('ix_dms_folders_parent_id'), table_name='dms_folders')
    op.drop_index(op.f('ix_dms_folders_org_id'), table_name='dms_folders')
    op.drop_index(op.f('ix_dms_folders_deleted_at'), table_name='dms_folders')
    op.drop_table('dms_folders')
    op.drop_index(op.f('ix_dms_tags_deleted_at'), table_name='dms_tags')
    op.drop_table('dms_tags')
    op.drop_index(op.f('ix_dms_categories_deleted_at'), table_name='dms_categories')
    op.drop_table('dms_categories')
    # ### end Alembic commands ###
