"use client";

import { AdminPageTemplate } from "@/components/ui/AdminPageTemplate";

export default function ReportsPage() {
  return (
    <AdminPageTemplate
      title="Reports"
      description="Manage and configure reports for the platform."
      entityName="Report"
      columns={["Report Name","Type","Generated By","Date"]}
    />
  );
}
